### ISSUE TITLE
CSS - Properties ordered by alphabet?

### ISSUE THREAD

**Issue by jackpandas** [foundersandcoders/facform#21]
Should we order CSS properties by alphabet as a production standard? Does this matter with CSS/SASS?

Example:
https://github.com/foundersandcoders/facform/blob/landing/public/css/main.css#L32-L40
@minaorangina @msmichellegar

**Comment by msmichellegar** [comment]
Yes! I love it!

**Comment by jackpandas** [comment]
Okay I'll add it to the production notes!

**Comment by msmichellegar** [comment]
Just to reiterate I'm so pleased someone else cares about alphabetising CSS properties.
