### ISSUE TITLE
Use normal bell?

### ISSUE THREAD

**Issue by MIJOTHY** [foundersandcoders/facform#35]
https://github.com/hapijs/bell/blob/master/lib/oauth.js#L199

**Comment by ronanyeah** [comment]
yeah they've updated the repo but they still haven't updated the npm package

**Comment by ronanyeah** [comment]
hence our sleazy copy version https://www.npmjs.com/package/fixed-bell

**Comment by MIJOTHY** [comment]
Fair enough, maybe a comment on their issue would nudge them to get it updated https://github.com/hapijs/bell/issues/102
