### ISSUE TITLE
Rethink Rethink!

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/facform#42]
I highly suggest we use Level. Rethink is going to throw up [all sorts](http://www.cthisspace.com/Allsorts.jpg) of issues!

**Comment by msmichellegar** [comment]
Yeah @rub1e I think you should look at this.

**Comment by jackpandas** [comment]
@izaakrogan 
![tumbleweed](https://cloud.githubusercontent.com/assets/12116201/8478533/0b78d2c8-20ca-11e5-839a-11c3d4bd7430.jpg)
